<a href="https://colab.research.google.com/github/MayVera/inteligenciaArtificial/blob/main/01%20de%20julio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])
a[1]=888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [21]:
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:]
print(aux.shape)
print(aux)

print('BEFORE/......')
print(b)
print(aux)

aux[1,1]=1000

print('AFTER/......')
print(b)
print(aux)


(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE/......
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER/......
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]
[[  22   33]
 [ 222 1000]]


In [23]:
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9 )
print(d.shape)
print(d)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [26]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
g=np.random.random((5,5))
print(g)

[[0.34958413 0.86518253 0.51980091 0.89747081 0.09359699]
 [0.78388196 0.43100251 0.59052494 0.96213542 0.50579887]
 [0.4050831  0.22025787 0.33077035 0.28160311 0.26261575]
 [0.7851023  0.13906211 0.26581878 0.35784345 0.63292395]
 [0.93660196 0.4291191  0.62763348 0.69743169 0.50275254]]


In [35]:
h=np.random.randint(1, 20, size=(4, 3))
print(h)
row=np.array([0,1,2,0])
cols=np.arange(4)
print(row)
print(cols)


[[ 7  3  3]
 [17  5  1]
 [18  9  9]
 [ 8 12 14]]
[0 1 2 0]
[0 1 2 3]
