<a href="https://colab.research.google.com/github/MayVera/inteligenciaArtificial/blob/main/01%20de%20julio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])
a[1]=888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [22]:
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:]
print(aux.shape)
print(aux)

print('BEFORE/......')
print(b)
print(aux)

aux[1,1]=1000

print('AFTER/......')
print(b)
print(aux)


(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE/......
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER/......
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]
[[  22   33]
 [ 222 1000]]


In [23]:
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9 )
print(d.shape)
print(d)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [24]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
g=np.random.random((5,5))
print(g)

[[0.94771051 0.77829837 0.55034165 0.7859259  0.68180138]
 [0.23204853 0.44522907 0.73148804 0.53920105 0.55333797]
 [0.41316855 0.54888478 0.30358686 0.85265038 0.58238692]
 [0.35162085 0.12433155 0.78952548 0.17169085 0.70540282]
 [0.87509502 0.9372564  0.51274872 0.80431617 0.55281747]]


In [26]:
h=np.random.randint(1, 20, size=(4, 3))
print(h)
row=np.array([0,1,2,0])
cols=np.arange(4)
print(row)
print(cols)


[[13  2 14]
 [ 6  1 18]
 [17  6  1]
 [ 2  4 14]]
[0 1 2 0]
[0 1 2 3]


In [27]:
a=np.random.randint(1,10,(3,4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())
tmp=a.mean(axis=1)
print(tmp)

aux=a.sum()
print(aux)
medianValue=np.median(a,axis=1)
print(medianValue)


[[2 1 3 9]
 [2 8 2 3]
 [5 3 8 5]]
4.25
4.25
[3.75 3.75 5.25]
51
[2.5 2.5 5. ]


In [30]:
#ORDENAR



#ORDENAR

b=np.random.randint(10, size=(5,)) # Generate an array of 5 random integers
print(b)
print(b.shape)
b.sort()
print(b)
print(b)

[6 6 1 6 5]
(5,)
[1 5 6 6 6]
[1 5 6 6 6]


In [31]:
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [35]:
string1=np.array(['desk','chair','bulb'])
string2=np.array(['lamp','bulb','chair'])

tmp1=np.intersect1d(string1,string2)
print(tmp1)
tmp2=np.union1d(string1,string2)
print(tmp2)
tmp3=np.setdiff1d(string1,string2)
print(tmp3)

string1=np.array(['desk','chair','bulb'])
string2=np.array(['lamp','bulb','chair'])
tmp4=np.in1d(string1,string2)
print(tmp4)

# in_both = np.in1d(string1, string2)
# print("Elementos en string1 que están también en string2:")
# print(string1[in_both])

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [43]:
#REPLICAS

aux=np.zeros((4,3))
print(aux)
replicate=np.array([1,2,3])
aux=aux+replicate
print(aux)
replicateCol=np.array([10,10,10])
print(replicateCol.shape)
replicateCol=np.reshape(replicateCol,(3,1))
print(replicateCol.shape)
aux=np.zeros((3,3))
aux1=aux+replicateCol
print(aux1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
