<a href="https://colab.research.google.com/github/MayVera/inteligenciaArtificial/blob/main/01dejulio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])
a[1]=888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [54]:
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:]
print(aux.shape)
print(aux)

print('BEFORE/......')
print(b)
print(aux)

aux[1,1]=1000

print('AFTER/......')
print(b)
print(aux)


(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE/......
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER/......
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]
[[  22   33]
 [ 222 1000]]


In [55]:
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9 )
print(d.shape)
print(d)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [56]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
g=np.random.random((5,5))
print(g)

[[0.53884625 0.54493956 0.01743878 0.67590404 0.87212373]
 [0.87274501 0.25902263 0.18077381 0.27092831 0.2374482 ]
 [0.64239624 0.87619195 0.95775383 0.2932035  0.36906784]
 [0.96891828 0.57143601 0.67197801 0.61692991 0.25543653]
 [0.10850536 0.69031371 0.2220874  0.69703391 0.86212571]]


In [58]:
tmp1=np.random.randint(1, 20,(4,4))
print(tmp1)
row=np.array([0,1,2,0])
cols=np.arange(4)
print(row)
print(cols)



[[16 19  2 11]
 [16 10 11 16]
 [15 18 10  8]
 [14  7  2  3]]
[0 1 2 0]
[0 1 2 3]


In [59]:
tmp1[row, cols]=100
print(tmp1)

[[100  19   2 100]
 [ 16 100  11  16]
 [ 15  18 100   8]
 [ 14   7   2   3]]


In [61]:
tmp1=np.random.randint(20, 50,(6,6))
print(tmp1)


[[38 23 41 28 28 25]
 [41 38 29 27 42 26]
 [22 41 42 45 22 29]
 [22 42 29 30 29 29]
 [32 46 44 32 36 36]
 [48 43 46 21 43 44]]


In [65]:
filter=(tmp1>45)
print(filter)
tmp2=tmp1[filter]
print(tmp2)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False  True False False False False]
 [ True False  True False False False]]
[46 48 46]


In [69]:
filter_impares= tmp1 % 2 !=1
print(filter_impares)
tmp3=tmp1[filter_impares]
print(tmp3)

[[ True False False  True  True False]
 [False  True False False  True  True]
 [ True False  True False  True False]
 [ True  True False  True False False]
 [ True  True  True  True  True  True]
 [ True False  True False False  True]]
[38 28 28 38 42 26 22 42 22 22 42 30 32 46 44 32 36 36 48 46 44]


In [72]:
tmp3=np.array([1,2,3,4,5,])
print(tmp3.dtype)
tmp3=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

int64
float64
