<a href="https://colab.research.google.com/github/MayVera/inteligenciaArtificial/blob/main/prueba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3]) #se crean los dos arreglos
b = np.array([4, 5, 6])
stacked_arrays = np.vstack((a, b)) #se crea la funcion np.vstack para que sea vertical
print(stacked_arrays)

[[1 2 3]
 [4 5 6]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arrays = np.hstack((a, b)) #se crea el np.hstack para que sea horizontal
print(stacked_arrays)

[1 2 3 4 5 6]


In [5]:
tmp = np.arange(15) # Crear el array tmp usando arange
result = tmp[(tmp >= 5) & (tmp <= 10)] #Obtener todos los elementos entre 5 y 10
print(result) #Mostrar el resultado


[ 5  6  7  8  9 10]


In [6]:
def pair_max(a, b): #Esta función toma como parámetros dos arrays
    return np.maximum(a, b) # Calcula el máximo elemento a nivel de elementos entre los arrays a y b.

# Definir matrices con la misma forma fuera de la función.
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
resultado = pair_max(a, b) #para calcular el máximo elemento a nivel de elementos entre a y b.
print(resultado)

[6 7 9 8 9 7 5]


In [7]:
def maxx(x, y): #maxx es el nombre de la función
    if x <= y: #compr si x es menor o = q y
        return y
    else:
        return x
resultado = maxx(2, 8) # calcula el máximo entre dos números enteros
print(resultado)

8


In [8]:
matriz_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(matriz_1d)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#Create random vector of size 10 and replace the maximum value by 0
random_vector = np.random.rand(10)
max_index = random_vector.argmax()
random_vector[max_index] = 0

print(random_vector)

[0.85421252 0.55855538 0.00984668 0.68046991 0.10413109 0.
 0.66707373 0.0652542  0.23463405 0.13522388]


In [12]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])
#Se encuentra en la segunda fila (índice 1) y la tercera columna (índice 2)

8


In [13]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [14]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr=np.array([1,2,3,4,5,6,7])
ultimos_4_numeros = arr[-4:]

print(ultimos_4_numeros)
#slicing

[4 5 6 7]


In [15]:
# Create a 3×3 numpy array of all True’s
# your code here
array_of_trues = np.ones((3, 3), dtype=bool)
array_of_trues = np.full((3, 3), True)
print(array_of_trues)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# Extract all odd numbers from arr

# Crear una matriz 3x3 de números enteros entre 0 y 9
matriz = np.random.randint(0, 10, (3, 3))

print("Matriz original:")
print(matriz)

# Encontrar los números impares
numeros_impares = matriz[matriz % 2 != 0]

print("\nNúmeros impares:")
print(numeros_impares)

Matriz original:
[[9 4 1]
 [4 6 0]
 [3 7 7]]

Números impares:
[9 1 3 7 7]


In [17]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [18]:
# Reverse a vector (first element becomes last)
vector = np.array([1, 2, 3, 4, 5])

print("Vector original:")
print(vector)

# Mover el último valor al primer lugar
vector = np.roll(vector, 1)

print("\nVector con el último valor como el primero:")
print(vector)

Vector original:
[1 2 3 4 5]

Vector con el último valor como el primero:
[5 1 2 3 4]


In [19]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
matriz = np.random.randint(59, 100, (10, 10))

print("Matriz:")
print(matriz)
print(matriz.max())
print(matriz.min())

Matriz:
[[66 84 60 76 81 78 75 66 96 96]
 [62 83 84 69 63 68 61 91 77 69]
 [74 88 78 66 60 98 84 98 85 69]
 [82 59 80 85 63 62 64 66 73 85]
 [87 81 93 79 74 65 75 98 95 76]
 [80 99 65 81 86 66 95 87 65 85]
 [61 72 74 69 73 97 87 96 82 98]
 [83 79 68 82 71 89 96 89 73 66]
 [98 91 61 59 77 88 98 73 61 67]
 [71 75 81 80 89 67 67 80 70 73]]
99
59


In [20]:
# Create a 3x3x3 array with random values
array_with_random_values = np.random.rand(3, 3, 3)
print(array_with_random_values)


[[[0.55765372 0.08119674 0.05312655]
  [0.38955681 0.08630802 0.35382898]
  [0.98157598 0.9168034  0.596987  ]]

 [[0.89955976 0.25553087 0.9362715 ]
  [0.06879435 0.07164906 0.23127581]
  [0.32019982 0.86644343 0.43858252]]

 [[0.13320689 0.4957561  0.48769932]
  [0.8746865  0.28261018 0.19763278]
  [0.54870538 0.33394816 0.12573406]]]


In [21]:
# Replace all odd numbers in arr with -1
def reemplazar_impares_bucle(arr):

  for i in range(len(arr)):
    if arr[i] % 2 != 0:
      arr[i] = -1
  return arr

mi_arr = [1, 2, 3, 4, 5]
nueva_arr = reemplazar_impares_bucle(mi_arr)
print(nueva_arr)

[-1, 2, -1, 4, -1]


In [22]:
# Create an array of type float
array_float = np.array([1, 2.5, 3, 4.1], dtype=float)

array_float = np.empty(4, dtype=float)
array_float[:] = [1, 2.5, 3, 4.1]

print(array_float)

[1.  2.5 3.  4.1]


In [23]:
# Convert a 1D array to a 2D array with 2 rows
arr = np.array([1, 2, 3, 4, 5, 6])

# Reestructurar el array para que tenga 2 filas
array_2d = arr.reshape(2, -1)  # -1 infiere el número de columnas

print(array_2d)


[[1 2 3]
 [4 5 6]]


In [24]:
# How to find common values between two arrays?
# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)


# Arrays de ejemplo
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Convertir arrays a conjuntos y encontrar la intersección
valores_comunes = set(Z1) & set(Z2)

# Convertir el conjunto de nuevo a una lista (opcional)
lista_valores_comunes = list(valores_comunes)

print(valores_comunes)
print(lista_valores_comunes)

{0, 5}
[0, 5]


In [25]:
#  Consider two random array A and B, check if they are equal
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

# Arrays aleatorios de ejemplo
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Verificar si los arrays son iguales elemento a elemento usando all()
son_iguales = np.all(A == B)

# Imprimir el resultado
print(f"Los arrays son iguales: {son_iguales}")

Los arrays son iguales: False
