<a href="https://colab.research.google.com/github/MayVera/inteligenciaArtificial/blob/main/prueba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3]) #se crean los dos arreglos
b = np.array([4, 5, 6])
stacked_arrays = np.vstack((a, b)) #se crea la funcion np.vstack para que sea vertical
print(stacked_arrays)

[[1 2 3]
 [4 5 6]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arrays = np.hstack((a, b)) #se crea el np.hstack para que sea horizontal
print(stacked_arrays)

[1 2 3 4 5 6]


In [6]:
tmp = np.arange(15) # Crear el array tmp usando arange
result = tmp[(tmp >= 5) & (tmp <= 10)] #Obtener todos los elementos entre 5 y 10
print(result) #Mostrar el resultado


[ 5  6  7  8  9 10]


In [10]:
def pair_max(a, b): #Esta función toma como parámetros dos arrays
    return np.maximum(a, b) # Calcula el máximo elemento a nivel de elementos entre los arrays a y b.

# Definir matrices con la misma forma fuera de la función.
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
resultado = pair_max(a, b) #para calcular el máximo elemento a nivel de elementos entre a y b.
print(resultado)

[6 7 9 8 9 7 5]


In [12]:
def maxx(x, y): #maxx es el nombre de la función
    if x <= y: #compr si x es menor o = q y
        return y
    else:
        return x
resultado = maxx(2, 8) # calcula el máximo entre dos números enteros
print(resultado)

8
